Repository OpenVoiceOS/ovos-installer, pull requests merged in 2024-10, with the labels that each got.

#175 [ansible/template] Make sure ovos-ggwave-listener starts
  ansible/roles/ovos_installer/templates/virtualenv/ovos-ggwave-listener.service.j2
Labels: bug

#176 [utils/common] Ask user permission to upload log on dpaste.com
  utils/common.sh
Labels: enhancement

#177 [ansible/template] Fix requirements
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/satellite-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/skills-requirements.txt.j2
Labels: bug, enhancement

#178 [readme] Add documentation about services start/stop
  README.md
Labels: documentation, enhancement

#170 Add autoconfig support to installer
  ansible/roles/ovos_installer/tasks/docker/composer.yml
  ansible/roles/ovos_installer/tasks/virtualenv/venv.yml
  ansible/roles/ovos_installer/templates/mycroft.conf.j2
Labels: enhancement, translation

#179 [ansible/venv] Less restrictive about the group for ovos-phal-admin
  ansible/roles/ovos_installer/templates/virtualenv/ovos-phal-admin.service.j2
Labels: bug, enhancement

#180 [ansible/venv] Add Matxa TTS when Catalan detected
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/satellite-requirements.txt.j2
Labels: bug, enhancement

#181 [ansible/templates] Use SOX player for wav and mp3 by default
  ansible/roles/ovos_installer/templates/mycroft.conf.j2
Labels: enhancement

#183 [ansible/venv] Use a wrapper for ovos-phal-admin systemd unit
  ansible/roles/ovos_installer/tasks/virtualenv/systemd.yml
  ansible/roles/ovos_installer/templates/virtualenv/ovos-phal-admin.service.j2
  ansible/roles/ovos_installer/templates/virtualenv/wrapper-ovos-phal-admin.sh.j2
Labels: bug, enhancement

#184 [utils/common] Check for Python version higher than 3.8
  utils/common.sh
Labels: bug, enhancement

#185 [utils/common] Check for AVX2 instead of AVX instruction
  docs/telemetry.md
  utils/common.sh
Labels: bug

#186 [tui/detect] Update from AVX to AVX2
  tui/locales/ca-es/detection.sh
  tui/locales/de-de/detection.sh
  tui/locales/en-us/detection.sh
  tui/locales/es-es/detection.sh
  tui/locales/eu-es/detection.sh
  tui/locales/fr-fr/detection.sh
  tui/locales/hi-in/detection.sh
  tui/locales/it-it/detection.sh
  tui/locales/nl-nl/detection.sh
  tui/locales/pl-pl/detection.sh
  tui/locales/pt-pt/detection.sh
Labels: translation

#187 [readme] Update documentation
  README.md
Labels: documentation, enhancement

#188 [ansible/venv] Install ggawave skill from PyPi
  ansible/roles/ovos_installer/templates/virtualenv/skills-requirements.txt.j2
Labels: enhancement

#190 [ansible/venv] Comment eastereggs skill until PR is merged
  ansible/roles/ovos_installer/templates/virtualenv/extra-skills-requirements.txt.j2
Labels: bug

#192 [installer] POSIX compliant
  installer.sh
Labels: bug

#194 [ansible/config] Disable GUI messages when headless
  ansible/roles/ovos_installer/templates/mycroft.conf.j2
Labels: enhancement

#197 [ansible/venv] Fix potential wrapper race condition
  ansible/roles/ovos_installer/templates/virtualenv/wrapper-ovos-phal-admin.sh.j2
Labels: bug, enhancement
