Repository OpenVoiceOS/ovos-installer, pull requests merged in 2024-04, with the labels that each got.

#66 added back button
  setup.sh
  tui/channels.sh
  tui/features.sh
  tui/locales/de-de/misc.sh
  tui/locales/en-us/misc.sh
  tui/locales/es-es/misc.sh
  tui/locales/fr-fr/misc.sh
  tui/locales/it-it/misc.sh
  tui/locales/nl-nl/misc.sh
  tui/locales/pt-pt/misc.sh
  tui/methods.sh
  tui/profiles.sh
  tui/satellite/host.sh
  tui/satellite/key.sh
  tui/satellite/main.sh
  tui/satellite/password.sh
  tui/satellite/port.sh
  tui/tuning.sh
Labels: enhancement

#69 [server] Implement server profile
  README.md
  ansible/roles/ovos_installer/tasks/docker/composer.yml
  ansible/roles/ovos_installer/tasks/main.yml
  ansible/roles/ovos_installer/tasks/ovos.yml
  ansible/roles/ovos_installer/tasks/virtualenv/systemd.yml
  ansible/roles/ovos_installer/tasks/virtualenv/venv.yml
  ansible/roles/ovos_installer/templates/mycroft.conf.j2
  ansible/roles/ovos_installer/templates/virtualenv/ovos-core.service.j2
  ansible/roles/ovos_installer/templates/virtualenv/ovos.service.j2
  ansible/roles/ovos_installer/templates/virtualenv/server-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/skills-requirements.txt.j2
  scenarios/scenario-ovos-skills-and-gui-rpi4b.yml
  scenarios/scenario-ovos-skills-and-gui.yml
  scenarios/scenario-ovos-skills.yml
  scenarios/scenario-satellite.yml
  scenarios/scenario-server.yml
  scenarios/scenario-uninstall.yml
  tui/features.sh
  tui/locales/de-de/profiles.sh
  tui/locales/en-us/profiles.sh
  tui/locales/es-es/profiles.sh
  tui/locales/fr-fr/profiles.sh
  tui/locales/it-it/profiles.sh
  tui/locales/nl-nl/profiles.sh
  tui/locales/pt-pt/profiles.sh
  tui/profiles.sh
  utils/constants.sh
Labels: enhancement

#71 Hindi language support added
  tui/language.sh
  tui/locales/hi-in/channels.sh
  tui/locales/hi-in/detection.sh
  tui/locales/hi-in/features.sh
  tui/locales/hi-in/finish.sh
  tui/locales/hi-in/methods.sh
  tui/locales/hi-in/misc.sh
  tui/locales/hi-in/profiles.sh
  tui/locales/hi-in/satellite.sh
  tui/locales/hi-in/summary.sh
  tui/locales/hi-in/telemetry.sh
  tui/locales/hi-in/tuning.sh
  tui/locales/hi-in/unistall.sh
  tui/locales/hi-in/welcome.sh
Labels: translation

#70 added uninstall in README
  README.md
Labels: documentation

#73 [scenario] Make sure scenario is valid
  tests/bats/scenario.bats
  utils/common.sh
  utils/scenario.sh
Labels: bug

#77 [FIX] Installer allowing invalid config.yaml files
  utils/scenario.sh
Labels: bug
