Repository OpenVoiceOS/ovos-installer, pull requests merged in 2024-08, with the labels that each got.

#124 [ansible/docker] Make sure xhost is installed when not EGLFS
  ansible/roles/ovos_installer/tasks/docker/setup-Arch.yml
  ansible/roles/ovos_installer/tasks/docker/setup-Debian.yml
  ansible/roles/ovos_installer/tasks/docker/setup-RedHat.yml
  ansible/roles/ovos_installer/tasks/docker/setup-Suse.yml
Labels: bug

#125 [ansible/docker] Handle xhost on Fedora
  ansible/roles/ovos_installer/tasks/docker/setup-RedHat.yml
Labels: enhancement

#126 [ansible/video] Detect WAYLAND_DISPLAY and dynamic DISPLAY
  ansible/roles/ovos_installer/tasks/docker/composer.yml
  ansible/roles/ovos_installer/tasks/video.yml
  ansible/roles/ovos_installer/templates/docker/env.j2
Labels: enhancement

#127 [ansible/docker] Make sure Docker GUI can run on stock Mark II
  ansible/roles/ovos_installer/tasks/docker/composer.yml
Labels: bug, enhancement

#128 [ansible/conf] Fix sentence_tokenize
  ansible/roles/ovos_installer/templates/mycroft.conf.j2
Labels: bug

#129 [mark2] Add missing rpi-backlight overlay
  ansible/roles/ovos_hardware_mark2/tasks/main.yml
  ansible/roles/ovos_hardware_mark2/tasks/touchscreen.yml
Labels: bug, enhancement

#131 Update Italian translation
  tui/locales/it-it/channels.sh
  tui/locales/it-it/detection.sh
  tui/locales/it-it/features.sh
  tui/locales/it-it/finish.sh
  tui/locales/it-it/methods.sh
  tui/locales/it-it/profiles.sh
  tui/locales/it-it/satellite.sh
  tui/locales/it-it/summary.sh
  tui/locales/it-it/telemetry.sh
  tui/locales/it-it/tuning.sh
  tui/locales/it-it/uninstall.sh
  tui/locales/it-it/welcome.sh
Labels: translation
