Repository OpenVoiceOS/ovos-installer, pull requests merged in 2024-02, with the labels that each got.

#48 Add openSUSE LEAP/Tumbleweed support
  ansible/roles/ovos_installer/tasks/docker/main.yml
  ansible/roles/ovos_installer/tasks/docker/setup-Suse.yml
  ansible/roles/ovos_installer/tasks/sound.yml
  ansible/roles/ovos_installer/tasks/tuning/governor.yml
  ansible/roles/ovos_installer/tasks/tuning/zram.yml
  ansible/roles/ovos_installer/tasks/virtualenv/gui.yml
  ansible/roles/ovos_installer/tasks/virtualenv/packages.yml
  utils/common.sh
Labels: enhancement

#51 [ansible/venv] Improve cleaning
  ansible/roles/ovos_installer/tasks/virtualenv/gui.yml
Labels: bug

#55 Add supported distros to README
  README.md
Labels: documentation

#59 feat/arch_support
  README.md
  ansible/roles/ovos_installer/tasks/docker/main.yml
  ansible/roles/ovos_installer/tasks/docker/setup-Arch.yml
  ansible/roles/ovos_installer/tasks/finalize.yml
  ansible/roles/ovos_installer/tasks/sound.yml
  ansible/roles/ovos_installer/tasks/tuning/governor.yml
  ansible/roles/ovos_installer/tasks/tuning/zram.yml
  ansible/roles/ovos_installer/tasks/virtualenv/gui.yml
  ansible/roles/ovos_installer/tasks/virtualenv/packages.yml
  tests/bats/packages.bats
  utils/common.sh
Labels: enhancement, feature
