Repository OpenVoiceOS/ovos-installer, pull requests merged in 2024-09, with the labels that each got.

#132 Update core-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
Labels: enhancement

#137 [ansible/gui] Add missing breeze-icon and fix #134
  ansible/roles/ovos_installer/tasks/virtualenv/gui.yml
Labels: bug

#140 [tui/method] Set default method to virtualenv
  tui/methods.sh
Labels: enhancement

#143 [ansible/virtualenv] core requirements
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
Labels: bug

#144 use pypi
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/extra-skills-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/satellite-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/server-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/skills-requirements.txt.j2
Labels: bug, enhancement

#147 More robust user home
  installer.sh
  utils/common.sh
Labels: enhancement

#148 [shell] Fix linting due to PR #147
  installer.sh
  utils/common.sh
Labels: enhancement

#153 [ci] Enable CI for pull request
  .github/workflows/linting.yml
Labels: enhancement

#151 speedup installer
  utils/argparse.sh
  utils/common.sh
Labels: enhancement, feature

#156 Rename REUSED_CACHED_ARTIFACTS->REUSE_CACHED_ARTIFACTS
  utils/argparse.sh
  utils/common.sh
Labels: bug, enhancement

#159 fix:pt
  tui/locales/pt-pt/channels.sh
  tui/locales/pt-pt/detection.sh
  tui/locales/pt-pt/features.sh
  tui/locales/pt-pt/finish.sh
  tui/locales/pt-pt/methods.sh
  tui/locales/pt-pt/profiles.sh
  tui/locales/pt-pt/satellite.sh
  tui/locales/pt-pt/summary.sh
  tui/locales/pt-pt/telemetry.sh
  tui/locales/pt-pt/tuning.sh
  tui/locales/pt-pt/uninstall.sh
  tui/locales/pt-pt/welcome.sh
Labels: enhancement, translation

#161 feat:gitlocalize
  .github/workflows/sync_tx.yml
  scripts/sync_translations.py
  translations/de-de/strings.json
  translations/en-us/strings.json
  translations/es-es/strings.json
  translations/fr-fr/strings.json
  translations/hi-in/strings.json
  translations/it-it/strings.json
  translations/nl-nl/strings.json
  translations/pt-pt/strings.json
  tui/locales/en-us/summary.sh
  tui/locales/fr-fr/channels.sh
  tui/locales/fr-fr/features.sh
  tui/locales/fr-fr/finish.sh
  tui/locales/fr-fr/methods.sh
  tui/locales/fr-fr/summary.sh
  tui/locales/fr-fr/telemetry.sh
  tui/locales/fr-fr/tuning.sh
  tui/locales/fr-fr/uninstall.sh
  tui/locales/hi-in/satellite.sh
  tui/locales/hi-in/telemetry.sh
  tui/locales/hi-in/tuning.sh
  tui/locales/hi-in/uninstall.sh
Labels: enhancement, translation
