Repository OpenVoiceOS/ovos-installer, pull requests merged in 2025-03, with the labels that each got.

#267 [ansible/venv] ONNXRuntime 1.21.0 breaks the listener
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
Labels: bug

#269 Galician translation
  translations/gl-es/strings.json
Labels: translation

#271 feat: basque support
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/satellite-requirements.txt.j2
  tui/language.sh
Labels: translation

#272 [tui] Add missing basque
  tui/language.sh
Labels: bug, translation

#273 [ansible/venv] Set TTS gender based on locale
  ansible/roles/ovos_installer/tasks/virtualenv/venv.yml
Labels: enhancement, translation
