Repository OpenVoiceOS/ovos-installer, pull requests merged in 2025-02, with the labels that each got.

#257 [ansible/venv] Set Rust messagebus as default
  ansible/roles/ovos_installer/tasks/ovos.yml
  ansible/roles/ovos_installer/tasks/virtualenv/bus.yml
  ansible/roles/ovos_installer/tasks/virtualenv/main.yml
  ansible/roles/ovos_installer/tasks/virtualenv/venv.yml
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/ovos-messagebus.service.j2
  ansible/roles/ovos_installer/templates/virtualenv/server-requirements.txt.j2
Labels: enhancement

#259 [ansible/ovos] Make sure .local belongs to user
  ansible/roles/ovos_installer/tasks/ovos.yml
Labels: bug

#260 [ansible/venv] Remove hivemind-presence as its breaks with LXML
  ansible/roles/ovos_installer/templates/virtualenv/listener-requirements.txt.j2
Labels: bug

#261 [ansible/persona] Add persona support
  ansible/roles/ovos_installer/tasks/ovos.yml
  ansible/roles/ovos_installer/tasks/virtualenv/systemd.yml
  ansible/roles/ovos_installer/templates/docker/env.j2
Labels: enhancement

#263 [ansible/tuning] Fix cpupower for Ubuntu 24.10
  ansible/roles/ovos_installer/tasks/tuning/governor.yml
Labels: bug

#264 Create funding-manifest-urls
  .well-known/funding-manifest-urls
Labels: documentation

#265 [utils] Fix GUi crash loop
  utils/common.sh
Labels: bug
