Repository OpenVoiceOS/ovos-installer, pull requests merged in 2025-04, with the labels that each got.

#274 [usage] Add opt-in usage metrics
  .github/workflows/scenarios-ubuntu2404.yml
  README.md
  ansible/roles/ovos_installer/templates/mycroft.conf.j2
  installer.sh
  scenarios/scenario-ovos-skills-and-gui-rpi4b.yml
  scenarios/scenario-ovos-skills-and-gui.yml
  scenarios/scenario-ovos-skills.yml
  scenarios/scenario-satellite.yml
  scenarios/scenario-server.yml
  scenarios/scenario-uninstall.yml
  setup.sh
  tests/bats/scenario.bats
  translations/en-us/strings.json
  tui/main.sh
  tui/usage_telemetry.sh
  utils/constants.sh
  utils/scenario.sh
Labels: enhancement

#276 [scripts] Add missing file for usage_telemetry.sh
  scripts/sync_translations.py
Labels: bug, translation

#277 [ansible/venv] Add ovos-tts-plugin-piper for offline method
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
  ansible/roles/ovos_installer/templates/virtualenv/satellite-requirements.txt.j2
Labels: bug

#278 [tui] Better description about the usage telemetry
  translations/en-us/strings.json
Labels: translation

#282 fix: restore support for python < 3.10
  ansible/roles/ovos_installer/templates/virtualenv/core-requirements.txt.j2
Labels: bug

#283 Update strings.json
  translations/ca-es/strings.json
Labels: translation

#290 added missing it-it file
  tui/locales/it-it/usage_telemetry.sh
Labels: translation

#293 [ansible/venv] Remove ovos-classifiers from satellite
  ansible/roles/ovos_installer/templates/virtualenv/satellite-requirements.txt.j2
Labels: bug
